name = "DieselGen"
uuid = "bc32595d-1e16-433f-a342-06d36c30239a"
authors = ["Kevin R. Moore <kevmoor@sandia.gov> and contributors"]
version = "0.1.0"

[deps]
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"

[compat]
ForwardDiff = "0.10, 1"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
